/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package khaslanainventaris;

import java.awt.Color;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.BorderFactory;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author rafidhp
 */
public class AddItemFrame extends javax.swing.JFrame {
    connection dbConn;
    private MainMenu parent;
    private java.util.List<Integer> categoryIdList = new java.util.ArrayList<>();
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AddItemFrame.class.getName());
    
    private void loadConditionComboBox() {
        conditionComboBox.removeAllItems();

        conditionComboBox.addItem("Tentukan Kondisi Barang");
        conditionComboBox.addItem("BAIK");
        conditionComboBox.addItem("KURANG BAIK");
        conditionComboBox.addItem("RUSAK");
    }
    
    private void loadCategoryComboBox() {
        try {
            String query = "SELECT * FROM categories";

            PreparedStatement ps = dbConn.conn.prepareStatement(query);
            ResultSet rs = ps.executeQuery();

            categoryComboBox.removeAllItems();
            categoryIdList.clear();

            // Placeholder
            categoryComboBox.addItem("Pilih Kategori");
            categoryIdList.add(-1); // dummy id

            while (rs.next()) {
                categoryComboBox.addItem(rs.getString("name"));
                categoryIdList.add(rs.getInt("id"));
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal load kategori\n" + e.getMessage());
        }
    }
    
    private void addFocusEffect(javax.swing.JTextField field) {
        field.setCaretColor(Color.WHITE);
    }
    
    
    private void addFocusEffectTextArea(javax.swing.JTextArea area) {
        area.setCaretColor(Color.WHITE);
    }
    

    /**
     * Creates new form AddCategoryFrame
     */
    public AddItemFrame(MainMenu parent) {
        initComponents();
        getContentPane().setBackground(new Color(30, 27, 38));
        // 🔹 CUSTOM SPINNER
        ((JSpinner.DefaultEditor) jumlahSpinner.getEditor()).getTextField().setBackground(new Color(30, 27, 38));
        ((JSpinner.DefaultEditor) jumlahSpinner.getEditor()).getTextField().setForeground(Color.WHITE);
        ((JSpinner.DefaultEditor) jumlahSpinner.getEditor()).getTextField().setBorder(null);
        jumlahSpinner.setBorder(BorderFactory.createLineBorder(new Color(153, 255, 51)));
        setLocationRelativeTo(null);
        dbConn = new connection();
        loadCategoryComboBox();
        loadConditionComboBox();
        getRootPane().setDefaultButton(addItemBtn);
        this.parent = parent;
        addFocusEffect(nameField);
        addFocusEffect(codeField);
        addFocusEffectTextArea(noteTextArea);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        nameField = new javax.swing.JTextField();
        addItemBtn = new javax.swing.JButton();
        backLink = new javax.swing.JLabel();
        categoryComboBox = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        codeField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jumlahSpinner = new javax.swing.JSpinner();
        jLabel7 = new javax.swing.JLabel();
        conditionComboBox = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        noteTextArea = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Google Sans", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 255, 51));
        jLabel1.setText("Khaslana Inventaris");

        jLabel2.setFont(new java.awt.Font("Google Sans", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Tambah Item");

        jLabel4.setFont(new java.awt.Font("Google Sans", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Pilih Kategori");

        nameField.setBackground(new java.awt.Color(30, 27, 38));
        nameField.setFont(new java.awt.Font("Google Sans", 0, 14)); // NOI18N
        nameField.setForeground(new java.awt.Color(255, 255, 255));
        nameField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 255, 51), 1, true));
        nameField.addActionListener(this::nameFieldActionPerformed);

        addItemBtn.setBackground(new java.awt.Color(30, 27, 38));
        addItemBtn.setFont(new java.awt.Font("Google Sans", 0, 14)); // NOI18N
        addItemBtn.setForeground(new java.awt.Color(255, 255, 255));
        addItemBtn.setText("Tambah");
        addItemBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 255, 51), 1, true));
        addItemBtn.addActionListener(this::addItemBtnActionPerformed);

        backLink.setForeground(new java.awt.Color(255, 255, 255));
        backLink.setText("Kembali");
        backLink.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                backLinkMousePressed(evt);
            }
        });

        categoryComboBox.setBackground(new java.awt.Color(30, 27, 38));
        categoryComboBox.setFont(new java.awt.Font("Google Sans", 0, 14)); // NOI18N
        categoryComboBox.setForeground(new java.awt.Color(255, 255, 255));
        categoryComboBox.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 255, 51), 1, true));
        categoryComboBox.addActionListener(this::categoryComboBoxActionPerformed);

        jLabel5.setFont(new java.awt.Font("Google Sans", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Kode Barang");

        codeField.setBackground(new java.awt.Color(30, 27, 38));
        codeField.setFont(new java.awt.Font("Google Sans", 0, 14)); // NOI18N
        codeField.setForeground(new java.awt.Color(255, 255, 255));
        codeField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 255, 51), 1, true));
        codeField.addActionListener(this::codeFieldActionPerformed);

        jLabel6.setFont(new java.awt.Font("Google Sans", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Nama Barang");

        jumlahSpinner.setFont(new java.awt.Font("Google Sans", 0, 14)); // NOI18N
        jumlahSpinner.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
        jumlahSpinner.setToolTipText("");
        jumlahSpinner.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 255, 51)));
        jumlahSpinner.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel7.setFont(new java.awt.Font("Google Sans", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Jumlah Barang");

        conditionComboBox.setBackground(new java.awt.Color(30, 27, 38));
        conditionComboBox.setFont(new java.awt.Font("Google Sans", 0, 14)); // NOI18N
        conditionComboBox.setForeground(new java.awt.Color(255, 255, 255));
        conditionComboBox.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 255, 51), 1, true));
        conditionComboBox.addActionListener(this::conditionComboBoxActionPerformed);

        jLabel8.setFont(new java.awt.Font("Google Sans", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Kondisi Barang");

        noteTextArea.setBackground(new java.awt.Color(30, 27, 38));
        noteTextArea.setColumns(20);
        noteTextArea.setForeground(new java.awt.Color(255, 255, 255));
        noteTextArea.setRows(5);
        noteTextArea.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 255, 51), 1, true));
        jScrollPane1.setViewportView(noteTextArea);

        jLabel9.setFont(new java.awt.Font("Google Sans", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Catatan");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addItemBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(backLink))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 405, Short.MAX_VALUE)
                                .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(conditionComboBox, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(codeField)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(64, 64, 64)
                                    .addComponent(jLabel1))
                                .addComponent(categoryComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel6)
                                .addComponent(jLabel7)
                                .addComponent(jLabel4)
                                .addComponent(jLabel5)
                                .addComponent(nameField)
                                .addComponent(jumlahSpinner))
                            .addComponent(jLabel9))
                        .addGap(0, 41, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(backLink))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(categoryComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(codeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jumlahSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(conditionComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(addItemBtn)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void nameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameFieldActionPerformed

    private void addItemBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addItemBtnActionPerformed
       try {
        // Ambil input
        int selectedIndex = categoryComboBox.getSelectedIndex();
        int categoryId = categoryIdList.get(selectedIndex);

        String code = codeField.getText().trim();
        String name = nameField.getText().trim();
        int jumlah = (int) jumlahSpinner.getValue();
        String condition = conditionComboBox.getSelectedItem().toString();
        String notes = noteTextArea.getText().trim();

        // VALIDASI

        // Kategori belum dipilih
        if (selectedIndex == -1 || categoryId == -1) {
            JOptionPane.showMessageDialog(this, "Silakan pilih kategori!");
            return;
        }

        // Kondisi belum dipilih (index 0 = placeholder)
        if (conditionComboBox.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(this, "Silakan pilih kondisi barang!");
            return;
        }

        // Field wajib
        if (code.isEmpty() || name.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Kode dan Nama barang wajib diisi!");
            return;
        }

        
        // CEK KODE UNIK
        String checkQuery = "SELECT COUNT(*) FROM items WHERE code = ?";
        PreparedStatement checkPs = dbConn.conn.prepareStatement(checkQuery);
        checkPs.setString(1, code);
        ResultSet rs = checkPs.executeQuery();

        if (rs.next() && rs.getInt(1) > 0) {
            JOptionPane.showMessageDialog(this, "Kode barang sudah digunakan!");
            return;
        }

        rs.close();
        checkPs.close();

        
        // INSERT DATA
        String insertQuery = """
            INSERT INTO items 
            (category_id, code, name, jumlah, item_condition, notes) 
            VALUES (?, ?, ?, ?, ?, ?)
        """;

        PreparedStatement ps = dbConn.conn.prepareStatement(insertQuery);

        ps.setInt(1, categoryId);
        ps.setString(2, code);
        ps.setString(3, name);
        ps.setInt(4, jumlah);
        ps.setString(5, condition);

        if (notes.isEmpty()) {
            ps.setNull(6, java.sql.Types.VARCHAR);
        } else {
            ps.setString(6, notes);
        }

        ps.executeUpdate();
        ps.close();

        //SUCCESS
        JOptionPane.showMessageDialog(this, "Item berhasil ditambahkan!");

        // 🔄 Reset form
        categoryComboBox.setSelectedIndex(0);
        conditionComboBox.setSelectedIndex(0);
        codeField.setText("");
        nameField.setText("");
        jumlahSpinner.setValue(1);
        noteTextArea.setText("");

        // Refresh table di main menu
        parent.refreshData();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal menambahkan item\n" + e.getMessage());
        }
    }//GEN-LAST:event_addItemBtnActionPerformed

    private void backLinkMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backLinkMousePressed
        this.dispose();
    }//GEN-LAST:event_backLinkMousePressed

    private void categoryComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categoryComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_categoryComboBoxActionPerformed

    private void codeFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codeFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codeFieldActionPerformed

    private void conditionComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_conditionComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_conditionComboBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addItemBtn;
    private javax.swing.JLabel backLink;
    private javax.swing.JComboBox<String> categoryComboBox;
    private javax.swing.JTextField codeField;
    private javax.swing.JComboBox<String> conditionComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jumlahSpinner;
    private javax.swing.JTextField nameField;
    private javax.swing.JTextArea noteTextArea;
    // End of variables declaration//GEN-END:variables
}
